# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/csec-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

if ENV['CI']
  namespace :coverage do
    desc 'Collates all result sets generated by the different test runners'
    task :report do
      require 'simplecov'
      require 'fileutils'

      SimpleCov.coverage_dir('coverage_results')
      files = Dir['**/coverage-report-unit-tests-*/coverage_*/.resultset.json']
      puts "pwd : #{system('pwd')}"
      puts "ls : #{system('ls')}"
      puts "ls coverage-report-unit-tests: #{system('ls coverage-report-unit-tests*')}"
      puts "ls lib: #{system('ls lib')}"
      SimpleCov.collate(files) do
        formatter SimpleCov::Formatter::HTMLFormatter
        refuse_coverage_drop
      end

      Dir['coverage-report-unit-tests-*'].each { |dir| FileUtils.rm_rf(dir) }
    end

    desc 'Removes all coverage_* directories'
    task :clear do
      require 'fileutils'
      Dir['coverage_*'].each { |dir| FileUtils.rm_rf(dir) }
    end
  end
end
