name: PR Continuous Integration
on:
  pull_request:
  workflow_dispatch:

jobs:
  run_rubocop:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure git
        run: 'git config --global init.defaultBranch main'
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2
      - uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88 # tag v1.165.1
        with:
          ruby-version: '3.3'
      - run: bundle
      - run: rubocop

  unit_tests:
    # TODO: remove below comment before release
    # needs: run_rubocop
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.4.10, 2.5.9, 2.6.10, 2.7.8, 3.0.6, 3.1.4, 3.2.2, 3.3.0]
    steps:
      - name: Configure git
        run: 'git config --global init.defaultBranch main'
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2

        # - curl is needed for Curb
        # - xslt is needed for older Nokogiris, RUBY_VERSION < 2.5
      - name: Install OS packages
        run: sudo apt-get update; sudo apt-get install -y --no-install-recommends libcurl4-nss-dev libxslt1-dev

      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88 # tag v1.165.1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Setup bundler
        run: bundle install

      - name: Bundle test environment
        run: BUNDLE_GEMFILE=Gemfile_test bundle install

      - name: Run Unit Tests
        run: bundle exec rake test
        env:
          VERBOSE_TEST_OUTPUT: true

      - name: Save coverage results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # tag v3.1.2
        with:
          name: coverage-report-unit-tests
          path: lib/coverage_*/.resultset.json

  simplecov:
    # TODO: remove below comment before release
    # needs: unit_tests
    runs-on: ubuntu-22.04
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Configure git
        run: 'git config --global init.defaultBranch main'
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2
      - uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88 # tag v1.165.1
        with:
          ruby-version: '3.1'
      - run: bundle
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # tag v3.0.2
      - name: Collate Coverage Results
        run: bundle exec rake coverage:report
      - name: Upload coverage results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # tag v3.1.2
        with:
          name: coverage-report-combined
          path: lib/coverage_results
          retention-days: 2
      - name: Simplecov Report
        uses: ./.github/actions/simplecov-report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          resultPath: lib/coverage_results/.last_run.json
          failedThreshold: 40
          failedThresholdBranch: 17

